# Generated by Django 2.0 on 2018-01-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('type', models.SmallIntegerField(choices=[(1, '邀请'), (2, '申请'), (4, '站内信')], verbose_name='站内信类型')),
                ('status', models.SmallIntegerField(choices=[(1, '草稿'), (2, '已发送'), (4, '已读'), (16, '被接受'), (8, '被拒绝')], default=1, verbose_name='站内信状态')),
                ('actor_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('refer_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_actor', to='contenttypes.ContentType')),
                ('refer_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_refer', to='contenttypes.ContentType')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_target', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
                'ordering': ('create_date',),
            },
        ),
    ]
