# Generated by Django 2.0 on 2018-01-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('team', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamupdate',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.Team', verbose_name='所属小组'),
        ),
        migrations.AddField(
            model_name='resource',
            name='owner_stu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='resource',
            name='owner_tch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher'),
        ),
        migrations.AddField(
            model_name='courseupdate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course', verbose_name='所属课程'),
        ),
        migrations.AddField(
            model_name='courseupdate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Teacher', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='courseupdate',
            name='resources',
            field=models.ManyToManyField(to='course.Resource', verbose_name='资源'),
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(to='course.Resource', verbose_name='资源'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_charge_course_set', to='accounts.Teacher', verbose_name='负责教师'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistant',
            field=models.ManyToManyField(related_name='help_course_set', to='accounts.Teacher', verbose_name='助教'),
        ),
    ]
