# Generated by Django 2.0 on 2018-01-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='小组名称')),
                ('status', models.SmallIntegerField(choices=[(1, '创建中'), (2, '已完成'), (4, '已锁定')], default=1, verbose_name='团队状态')),
                ('belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course', verbose_name='本组所属课程')),
                ('members', models.ManyToManyField(related_name='added_groups', to='accounts.Student', verbose_name='组员')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_groups', to='accounts.Student', verbose_name='组长')),
            ],
            options={
                'ordering': ('create_date',),
            },
        ),
    ]
